title: José C.S. Curet
description: Computer Science and Communications student. Interested on halt and reverse the impact of climate change using applied AI and Machine Learning.
show_downloads: false
theme: jekyll-theme-minimal
